### ISSUE TITLE
Feedback! And some thoughts on Lunge v/s Artifact

### ISSUE THREAD

**Issue by felix91gr** [JohnnyDevo/The-Mystic-Project#11]
First of all, my feedback:

I think this mod is pretty great. I've seen it in Rhapsody's videos and today I finally tried it myself. Had a blast of a run with that Arte that increases in power overtime (a la genetic algorithm) + bent spoon 😄 

Now, regarding my thoughts on Lunge and its interaction with Artifact: 

Since the loss of Dex is separated from the regaining of Dex at the end of turn, I sort of expected it to give me 4 Dex at the end of turn after using it while having Artifact-ed myself. It did not, however, and that made me come here.

Before suggesting that it should behave differently, I feel like I should point out that "temporary" debuffs don't give buffs when they are shot at Artifact-ed enemies (e.g. Dark Shackles: shoot it at a fresh Sentry, and you will not give them +8 str at the end of their turn). That's the closest example from the canon behavior of the game, that I know of, to our particular scenario.

What are your thoughts on this? Should it remain like Dark Shackles, or should it establish its own canon? I'm not sure, I think it makes sense both ways.

Also, has someone discussed these "canonical behavior" things already in the mod community? I would love to read more about it, if you have any links to share ☺️ 

---

References:
* Section where artifact is consulted before applying delayed Dex buff: https://github.com/JohnnyDevo/The-Mystic-Project/blob/e999a939a8aea55c76e7e82133df00fc0fc2f086/src/main/java/mysticmod/cards/Lunge.java#L41-L48

**Comment by NellyDevo** [comment]
hey, thanks for the feedback!

Yeah, I purposefully made temporary dex down behave the same way as dark shackles and piercing wail. Temporary negative strength behaves as a single debuff, and I assume they made it affect strength itself so that the player doesn't have as much math to do (10 str rather than 14 str - 4 temp negative str).

I opted to make it behave the same way because I believe it's more confusing to have the interactions inconsistent.

**Comment by felix91gr** [comment]
Awesome, I think it's probably the right call. Also good to know that you thought about this from the beginning! 😊
