### ISSUE TITLE
Cantrip Interaction with Artifact

### ISSUE THREAD

**Issue by fkinghatesigningup** [JohnnyDevo/The-Mystic-Project#4]
Cantrip was eating my artifact charges, so were cards with technical.  Played like 4 runs on a10; the class is weak now.

**Comment by NellyDevo** [comment]
Did you have "Arcane Accuracy"? On each trigger of arcane accuracy, it gives you one "strength for turn", and the "lose strength at end of turn" half of that is a debuff, which consumes artifact.

**Comment by fkinghatesigningup** [comment]
That's most likely the reason.
