### ISSUE TITLE
Discipline does not count towards Deck Of Many Things

### ISSUE THREAD

**Issue by SilentJ28** [JohnnyDevo/The-Mystic-Project#6]
Discipline says "Begin each turn as if you had already played one Spell and one Arte" but having the counter be at 2 each (with discipline providing the first one of each) does not prevent Deck Of Many Things life loss trigger

**Comment by NellyDevo** [comment]
Currently working as intended, with the reasoning that if I were to introduce this sort of logic, then discipline would completely negate gemini form.

Thankyou for the feedback, though!
