### ISSUE TITLE
Greater Invisibility(+) exhausts where it shouldn't

### ISSUE THREAD

**Issue by Jedi515** [JohnnyDevo/The-Mystic-Project#8]
P much says enough in the title. Idk if it's strange spoon i bought (exhaust cards have 50% chance to be discarded on play), but sometimes GI just exhausts no matter if i've played 1, 2 or more artes (spell counter is always at 2+ aswell)
I don't have anything else that affects exhaust mechanic so idk what else could cause it.

**Comment by NellyDevo** [comment]
The cause was pure and simple oversight.

Thanks for the report! I'll just include it in a hotfix in a few.
